### ISSUE TITLE
[housekeeping] qa build images

### ISSUE THREAD

**Issue by austinorr** [sitkatech/nereid#5]
@NickLacunha are the following files still needed?

 - docker-compose.qa.build.yml (identical to dev.build except the images)
 - docker-compose.qa.env.yml
 - docker-compose.qa.ports.yml

I notice that the scripts\build_qa.bat no longer refers to them either, and appears correct.

**Comment by NickLacunha** [comment]
Yes, correct. I've removed these in my latest commit; hash 46cbfc07ef507938b2a6d4d99086061385d89fcf
